
== Application Security Dashboard

The Application Security dashboard provides you with a centralized view of the top code security vulnerabilities and misconfigurations identified across your connected code integrations on Prisma Cloud. View and analyze contextual visulaizations of high priority errors surfaced in these key vectors:

* Total Repositories by Error Severity
* Error Burndown Chart
* Top Errors by Policy
* IaC errors by Category
* Top CVSS Score Vulnerabilities
* Top Non-Compliant Package Licenses
* Top Secret Risk Factors

Navigate to *Dashboards > Application Security* to view and manage the dashboard. The dashboard is only available if you have subscribed to Code Security on Prisma Cloud. 

=== Total Errors

The *Total Errors* bar provides a summary of code errors classified by  Critical, High, Medium, Low and Info error severity.
View custom results for all Application Security errors using filters to narrow your investigation into a specific *Repository, Code Category* or *Severity*. Select multiple repositories, code categories and severity at once to find critical errors that may need immediate remediation. Filtering the data updates all visualizations on the dashboard. Reset the filters to revert back to default filter settings.

Select the number corresponding to a severity to view contextual results for code errors by severity. Results are displayed  on the *Code Security > Projects > Overview* page. You can also execute remedial actions if necessary on the  *Projects* page.


=== Code Errors Visualizations

The code errors are actionable and are grouped in these areas:

[cols="30%a,70%a"]
|===

|*Total Repositories by Error Severity*
|Provides a bar graph visualization of  the  top trending repositories to have a maximum number of Critical or High severity errors. The representing data is periodically updated, and you can verify the accuracy of the last scan by hovering on the timestamp.

|*Error Burndown Chart*
|View the trend for code errors and pull requests for repositories that are scanned using Prisma Cloud.
Code Issues over time: Visualizes the trendline of code errors from the last 30 days of a default branch in an integrated repository . The data also gives you an understanding of when the errors occurred by monitoring data on *Opened Earlier*, *Fix Pending*, and *Suppressed*. You can also see if any remedial actions were taken on the same day by monitoring data on *Fixed Today* and *Opened Today*.

|*Top Errors by Policy*
|Provides a view of policies that have the highest error count. The data contextualized here is after periodic scans with timestamp available for you to see. With the high count of errors within a policy, you can also have information of the type of policy by *Labels*, and the *Severity*. Selecting the policy directs you to *Policies* for more actionable information. While selecting the error count directs you to *Code Security > Projects > Overview* to execute a remedial action if necessary.

|*IaC errors by Category*
|Provides a summarized view for misconfigurations seen in IaC category. The count in each category is the number of misconfigurations identified and on selecting the count directs you to *Code Security > Projects > IaC Misconfiguration* where you can choose to execute a remedial action on *Resource Explorer*.

|*Top CVSS Score Vulnerabilities*
|Lists the highest CVSS score identified across vulnerability scans. You also see the Risk Factors, the potentially compromised CVE with *Severity*, and *Count*. Selecting the count directs you to *Code Security > Projects > Vulnerabilities* with the CVE errors preselected.

|*Top Non-Compliant Package Licenses*: 
|Provides insight into non-compliant package licenses that are being used in the repositories. The data shows the number of repositories that are potentially exposed due to usage of non-compliant package licenses. The count shows the total number of instances the non-compliant package is used. Selecting the count directs you to  *Code Security > Projects > Overview* with the non-compliant package already filtered. You can choose  to execute a manual remedial action on *Overview* if necessary.

|*Top Secret Risk Factors*
|TBD

|===