
== Application Security Dashboard

The Application Security dashboard provides you with a centralized view of the top code security vulnerabilities and misconfigurations identified across your connected code integrations on Prisma Cloud. View and analyze contextual visulaizations of high priority errors surfaced in these key vectors:

* Total Repositories by Error Severity
* Error Burndown Chart
* Top Errors by Policy
* IaC errors by Category
* Top CVSS Score Vulnerabilities
* Top Non-Compliant Package Licenses
* Top Secret Risk Factors

Navigate to *Dashboards > Application Security* to view and manage the dashboard. The dashboard is only available if you have subscribed to Code Security on Prisma Cloud. 

=== Total Errors

The *Total Errors* bar provides a summary of code errors  across severity of  Critical, High, Medium, Low and Info.
You can see custom results for all Code Security errors using filters that allow you to narrow your investigation to a specific *Repository, Code Category* or *Severity* . You can select multiple repositories, code categories and severity at once to narrow your investigation to find critical errors that may need immediate remediation . Filtering the data updates all visualizations on the dashboard. The reset filters allow you to revert back to default filter settings.
You can also see contextual results for code errors by severity when selecting the number corresponding to the severity  giving you access to the results on *Code Security > Projects > Overview*. On *Projects* you can execute remedial actions if necessary.


=== Code Errors Visualization

The code errors are actionable and are grouped in these areas:

* *High-risk code errors by severity*: The *Top Repositories buy High Risk Code Error Count* provides a bar graph visualization of  the  top trending repositories to have a maximum number of Critical or High severity errors. The representing data is periodically updated, and you can verify the accuracy of the last scan by hovering on the timestamp.

* *Historical data for code issues and pull requests*: View the trend for code errors and pull requests for repositories that are scanned using Prisma Cloud.
** *Code Issues over time*: Visualizes the trendline of code errors from the last 30 days of a default branch in an integrated repository . The data also gives you an understanding of when the errors occurred by monitoring data on *Opened Earlier*, *Fix Pending*, and *Suppressed*. You can also see if any remedial actions were taken on the same day by monitoring data on *Fixed Today* and *Opened Today*.

* *Common policy errors*: The *Common Errors by Policy* provides a view of policies that have the highest error count. The data contextualized here is after periodic scans with timestamp available for you to see. With the high count of errors within a policy, you can also have information of the type of policy by *Labels*, and the *Severity*. Selecting the policy directs you to *Policies* for more actionable information. While selecting the error count directs you to *Code Security > Projects > Overview* to execute a remedial action if necessary.

* *Licensing errors in non-compliant packages*: The *Top Non-compliant Package licenses* provides insight into non-compliant package licenses that are being used in the repositories. The data shows the number of repositories that are potentially exposed due to usage of non-compliant package licenses. The count shows the total number of instances the non-compliant package is used. Selecting the count directs you to  *Code Security > Projects > Overview* with the non-compliant package already filtered. You can choose  to execute a manual remedial action on *Overview* if necessary.

* *IaC errors in code categories*: The IaC Errors by Category provides a summarized view for misconfigurations seen in IaC category. The count in each category is the number of misconfigurations identified and on selecting the count directs you to *Code Security > Projects > IaC Misconfiguration* where you can choose to execute a remedial action on *Resource Explorer*.

* *Vulnerabilities seen in CVE from CVSS score*: The *Top CVSS Score Code Vulnerabilities* lists the highest CVSS score identified across vulnerability scans. You also see the Risk Factors, the potentially compromised CVE with *Severity*, and *Count*. Selecting the count directs you to *Code Security > Projects > Vulnerabilities* with the CVE errors preselected.

