== Code to Cloud Dashboard

Prisma Cloud’s *Code to Cloud* dashboard provides a continulously updated snapshot view into the security posture of your cloud environment. Quickly get answers to questions such as:

* What assets do I have in the cloud?
* What is my organization's security risk posture?
* How do I track progress in securing our cloud infrastructure by application, team, and business unit?
* How can I evaluate my DevOps teams' progress in achieving our key security objectives?

The Code to Cloud Dashboard provides you with metrics and data around each of these key questions, helping you quantify and showcase your progress with your entire security team. Use Prisma Cloud's out of the box Dashboards to track your operational progress across every phase of your application development lifecycle Code, Build, Deploy and Run. Dashboards help you save time by streamlining tracking and reporting, eliminating the need to create multiple saved views across different areas of various products.

=== Live Event Tracker 

The event tracker allows you to check the pulse of your security posture in real time. The *Dashboards > Code to Cloud > Live Event Tracker* provides a stream of updates tracking changes across key metrics such as, Threats blocked/prevented, Alerts remediated/resolved, Critical alerts generated and more.

Use the security events live stream to quickly assess the potential threat activity taking place in your cloud environment. You then have the option to double-click on event to dive deeper and take timely action. Select *See All Events* to see a list of all real-time events. Click any event to navigate to the specific alert and investigate further. 

=== Cloud Inventory
Code to Cloud Inventory provides a panoramic birds eye view of your entire cloud estate, helping you understand how well your organization is embracing security best practices across your cloud environment, from individual resources to the entire code pipeline. 

==== Code/Build Inventory

The Code/Build inventory widget surfaces metrics derived from the monitoring and scanning of hundreds of code repositories across three repository systems secured by Prisma Cloud scanners IaC/SCA, Secrets, and SAST. Data from devs actively using IDE extensions / interacting with Prisma Clous PR recommendations are also included.

*Question* - Will we be able to click on KPIs like Repositories with Hard Fails configured and investigate further? I think we need more details here on the value we are adding with the trendlines and roll-up of Repos, Repos with Hard Fails etc.

==== Deploy Inventory

Use the Deploy Inventory widget to identify at a glance when malicious images are deployed in your development environment. 

Runtime defense is the set of features that provide predictive protection for containers and threat based active protection for running containers, hosts and serverless functions.
Predictive protection includes capabilities like determining when a container runs a process not included in the origin image or creates an unexpected network socket.
Threat based protection includes capabilities like detecting when malware is added to a workload or when a workload connects to a botnet.

*Question* - Should we describe each metric tracked here and the value it adds such as the following for Trusted Images?

Use Trusted Images to declare, by policy, which registries, repositories, and images you trust, and how to respond when untrusted images are initiated in your environment. If an untrusted image runs, Prisma Cloud raises an alert, and can optionally blocks the container containing the image from running.

==== Runtime Inventory

The Runtime Inventory widget helps you quantify and demonstrate that you are reducing risk and proactively preventing breaches. The Urgent Alerts view shows progress in remediation and the burn down of urgent incidents helping you track and show progress. 

*Question* - Should we offer a recommendation here? For instance, "Ensure that a minnimum of 50% of your Workload is protected by agents to proactively mitigate risk."

=== Top Issues by Business Unit

You also have the option to segment your top security risks by Applications or Account owner to further track and monitor critical vulnerabilities and exposures. 

Provide breakdown of Total Environment Rollup and visualizations by BU available OOTB. 

The Create Business Unit button allows you to create your own custom allocation of account and application owners to obtain more granular results on risks by individual stakeholders. 
